version: '3.9'

services:
  health-postgres:
    image: postgres:15
    container_name: health_postgres
    restart: always
    environment:
      POSTGRES_DB: healthdb
      POSTGRES_USER: health_user
      POSTGRES_PASSWORD: health_pass
    ports:
      - "5433:5432"
    volumes:
      - health_pg_data:/var/lib/postgresql/data
    networks:
      - health_net

  redis:
    image: redis:7.2
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - health_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - health_net

networks:
  health_net:

volumes:
  health_pg_data:
