spring:
  application:
    name: health-data-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5433/healthdb
    username: health_user
    password: health_pass

  liquibase:
    enabled: false

logging:
  level:
    org.springframework.r2dbc: DEBUG
